name = "heisenberg"
compatibility_date = "2026-03-18"

[env.production]
routes = [
  { pattern = "heisenberg.pages.dev", zone_name = "heisenberg.pages.dev" }
]

[build]
command = "cd heisenberg && npm install && npm run build"
cwd = "."
watch_paths = ["heisenberg/src/**/*.{ts,tsx,css}"]

[build.upload]
dir = "heisenberg/dist"

[pages]
project_name = "heisenberg"
